kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-iam-operand
subjects:
- kind: ServiceAccount
  name: ibm-iam-operand
roleRef:
  kind: Role
  name: ibm-iam-operand
  apiGroup: rbac.authorization.k8s.io
